name: Release TestFairy Nativescript SDK
on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '15.12.0'
    - name: Install Dependencies
      run: |
        brew install carthage
        npm install -g nativescript@7.0.11
        tns usage-reporting disable
        tns error-reporting disable
    - name: Update Native SDK
      run: |
        ANDROID_SDK_VERSION=1.12.12
        IOS_VERSION=1.29.2
        curl -s -L https://maven.testfairy.com/com/testfairy/testfairy-android-sdk/${ANDROID_SDK_VERSION}/testfairy-android-sdk-${ANDROID_SDK_VERSION}.aar -o src/platforms/android/testfairy-android-sdk.aar
        echo "github \"testfairy/testfairy-carthage\" == ${IOS_VERSION}" > Cartfile
        cat Cartfile
        echo ${GITHUB_REF##*/} > RELEASE_TAG
        sed -i '' "s/\"version\":.*/\"version\":\"$(cat RELEASE_TAG)\",/g" src/package.json
        carthage update
        rm -rf src/platforms/ios/TestFairySDK.*
        cp -R Carthage/Build/iOS/TestFairy.framework* src/platforms/ios/.
        rm -rf Carthage
    - name: Release Nativescript to npm
      run: |
        pwd
        ls -lsrta
        cd ../publish
        sh pack.sh
        cd package
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
